import convert
from ahk import AHK

#NAVIGATE MENU IN-BETWEEN GAMES.  NOT TOTALLY SURE IF NEEDED, MIGHT BE DELEGATED TO PLAYER OR YUUMI

#JOIN INVITE

#SELECT ROLE

#ACCEPT QUEUE

#CHAMP SELECT
    #CHAMP TO BAN

#AFTER-GAME SCREEN

#WAY TO QUIT IF DUO LEAVES (IF PARTY OWNER -> QUIT)